### ISSUE TITLE
common roles 在centos下disable Selinux 有问题，急需解决

### ISSUE THREAD

**Issue by chendelin1982** [Websoft9/ansible-roles#12]
TASK [common : temporarily disable Selinux] ************************************
fatal: [47.111.104.181]: FAILED! => {"changed": true, "cmd": "setenforce 0", "delta": "0:00:00.020509", "end": "2019-11-17 19:42:28.991492", "msg": "non-zero return code", "rc": 1, "start": "2019-11-17 19:42:28.970983", "stderr": "setenforce: SELinux is disabled", "stderr_lines": ["setenforce: SELinux is disabled"], "stdout": "", "stdout_lines": []}

**Comment by Mozlk** [comment]
已解决
